ItemsData={
	--普通物品
	{name="DoorKey",chinese="门钥匙",type=Item},
	{name="BridgeKey",chinese="桥钥匙",type=Item},
	{name="ThiefKey",chinese="盗贼钥匙",type=Item},
	{name="Vulnerary",chinese="伤药",type=Item},
	{name="HolyWater",chinese="圣水",type=Item},
	--能力提升
	{name="PowerRing",chinese="力量戒指",type=Item,price=2550,pow=4},
	{name="SecretBook",chinese="秘传书",type=Item,price=2550,skl=5},
	{name="SpeedRing",chinese="速度戒指",type=Item,price=2550,spd=6},
	{name="GoddessStatue",chinese="女神像",type=Item,price=2550,lck=7},
	{name="DragonShield",chinese="龙盾",type=Item,price=2550,def=3},
	{name="Talisman",chinese="护身符",type=Item,price=2550,mdf=7},
	{name="AngelCloth",chinese="天使衣",type=Item,price=2550,mhp=9},
	{name="Manual",chinese="手册",type=Item,wpnLv=5},
	{name="Boots",chinese="靴",type=Item,price=2550,mov=4},
	--转职
	{name="KnightMedal",chinese="骑士勋章",type=Item},
	{name="BraverProof",chinese="勇者证",type=Item},
	{name="BishopRing",chinese="司祭戒指",type=Item},
	{name="HeavenWhip",chinese="天空鞭",type=Item},
	{name="OleanBow",chinese="奥利安弓",type=Item},
	--卡
	{name="SilverCard",chinese="银卡",type=Item},
	{name="MemberCard",chinese="会员卡",type=Item},
	--宝珠
	{name="EarthOrb",chinese="大地珠",type=Item},
	{name="StarOrb",chinese="星珠",type=Item},
	{name="LightOrb",chinese="光珠",type=Item},
	--龙石
	{name="FireDragonStone",chinese="火龙石",type=DragonStone,weight=3,might=16,hit=80,def=12},
	{name="GodDragonStone",chinese="神龙石",type=DragonStone,weight=1,might=12,hit=100,def=15},
	{name="DemonDragonStone",chinese="魔龙石",type=DragonStone,weight=6,might=18,hit=90,def=16},
	{name="EarthDragonStone",chinese="地龙石",type=DragonStone,weight=10,might=20,hit=70,def=23},
}
