--[[
Lord,领主,18,5,0,3,7,0,7,0,7,剑E
Thief,盗贼,16,2,0,1,7,0,1,0,7,剑E
Commander,指挥官,16,1,0,1,6,0,4,10,6,--
Shooter,弩车射手,20,5,0,1,3,0,14,0,4,--
Soldier,士兵,16,3,0,3,3,0,3,0,6,枪E
,龙人,18,0,0,1,1,0,1,1,6,--
Archer,弓箭手,16,5,0,3,4,0,6,0,5,弓E
Sworder,剑士,16,3,0,9,11,0,4,0,7,剑E
术士,16,0,3,1,3,0,2,3,6,魔E
僧侶,16,0,1,1,4,0,3,6,5,杖E
修女,16,0,1,1,3,0,1,8,5,杖E
装甲兵,18,6,0,2,0,0,11,0,5,枪E
骑士,18,5,0,2,6,0,7,0,9,剑E枪E
佣兵,16,4,0,8,10,0,5,0,7,剑E
战士,20,5,0,1,7,0,3,0,6,斧E
海盗,18,5,0,1,6,0,4,0,6,斧E
暗法师,16,0,2,1,3,0,4,3,6,魔E
猎人,18,6,0,4,6,0,3,0,6,弓E
飞马骑士,16,4,2,5,7,0,5,6,8,枪E
圣骑士,22,7,1,5,7,0,8,6,10,剑E枪D
狙击手,24,7,1,8,9,0,7,3,7,弓C
剑圣,22,5,1,11,13,0,6,3,8,剑C
贤者,22,3,4,2,4,0,3,5,6,魔D杖E
教主,22,1,3,2,4,0,3,8,6,魔E杖D
教主,22,1,3,2,4,0,3,8,6,魔E杖D
龙骑士,20,8,1,5,7,0,10,3,10,枪D斧E
将军,28,8,1,3,4,0,15,3,6,枪D弓E
勇者,22,6,1,10,12,0,7,3,8,剑D斧E
勇士,26,7,0,2,8,0,5,1,7,斧D弓E
骑手,20,6,1,6,8,0,6,3,9,剑E弓D
狂战士,24,7,0,2,7,0,6,0,7,斧D
法师,22,2,3,2,4,0,4,6,6,魔D杖E
隼骑士,20,6,1,5,7,0,7,8,10,剑E枪D
火龙,18,8,0,5,5,0,10,5,6,--
魔龙,18,0,7,2,0,0,12,11,6,--
地龙,18,14,0,10,8,0,14,19,6,--
神龙,18,10,0,8,5,0,16,12,6,--
]]

ClassesData={
	{name="",chinese=""},
--王族
	{name="Lord",chinese="领主"},
	{name="Prince",chinese="王子"},
	{name="Princess",chinese="公主"},
	{name="Queen",chinese="皇后"},
	{name="King",chinese="国王"},
	{name="Emperor",chinese="皇帝"},
--平民
	{name="Villager",chinese="村民"},
	{name="Dancer",chinese="舞者"},
	{name="Bard",chinese="吟游诗人"},
--骑士
	{name="Cavalier",chinese="骑兵",isKnight=true},
	{name="Knight",chinese="骑士",isKnight=true},

	{name="SwordArmor",chinese="剑甲兵"},
	{name="SwordCavalier",chinese="剑骑兵",isKnight=true},
	{name="SwordKnight",chinese="剑骑士",isKnight=true},

	{name="LanceArmor",chinese="枪甲兵"},
	{name="LanceCavalier",chinese="枪骑兵",isKnight=true},
	{name="LanceKnight",chinese="枪骑士",isKnight=true},

	{name="AxeArmor",chinese="斧甲兵"},
	{name="AxeCavalier",chinese="斧骑兵",isKnight=true},
	{name="AxeKnight",chinese="斧骑士",isKnight=true},

	{name="ArchArmor",chinese="弓甲兵"},
	{name="ArchKnight",chinese="弓骑士",isKnight=true},
	{name="BowKnight",chinese="弩骑士",isKnight=true},

	{name="FreeKnight",chinese="自由骑士"},
	{name="PriestKnight",chinese="神官骑士"},
	{name="MagicKnight",chinese="魔法骑士"},
	{name="LordKnight",chinese="领主骑士",isKnight=true},
	{name="DukeKnight",chinese="公爵骑士"},
	{name="MasterKnight",chinese="统帅骑士"},
	{name="Paladin",chinese="圣骑士",isKnight=true},
	{name="SilverKnight",chinese="银骑士",isKnight=true},
	{name="GoldenKnight",chinese="金骑士",isKnight=true},
--空军
	{name="PegasusKnight",chinese="天马骑士",isAirForce=true},
	{name="DragonKnight",chinese="龙骑士",isAirForce=true},
	{name="DragonMaster",chinese="龙骑统帅",isAirForce=true},
	{name="FalconKnight",chinese="隼骑士",isAirForce=true},
--剑术系
	{name="Sworder",chinese="剑士"},
	{name="MagicSworder",chinese="魔剑士"},
	{name="SwordMaster",chinese="剑圣"},
	{name="Mercenary",chinese="佣兵"},
	{name="Braver",chinese="勇者"},
--弓箭系
	{name="Archer",chinese="弓箭手"},
	{name="Sniper",chinese="狙击手"},
	{name="Hunter",chinese="猎人"},
	{name="HorseArcher",chinese="马弓手"},

	{name="Ballista",chinese="弩车"},

	{name="Soldier",chinese="士兵"},
	{name="ArmorSoldier",chinese="装甲兵",isArmor=true},
	{name="General",chinese="将军",isArmor=true},

	{name="Barbarian",chinese="野蛮人"},
	{name="Bandit",chinese="土匪"},
	{name="Fighter",chinese="战士"},
	{name="Berserker",chinese="狂战士"},
	{name="Warrior",chinese="勇士"},
	{name="MountainThief",chinese="山贼"},
	{name="Pirate",chinese="海盗"},
--隐秘系
	{name="Thief",chinese="盗贼"},
	{name="Bandit",chinese="侠盗"},
	{name="Assassin",chinese="刺客"},

	{name="Commander",chinese="指挥官"},
	{name="Mamkute",chinese="龙人"},

	{name="Cleric",chinese="传教士"},
	{name="Warlock",chinese="术士"},
	{name="Mage",chinese="法师"},
	{name="DarkMage",chinese="暗法师"},
	{name="DarkBishop",chinese="暗教主"},
	{name="Monk",chinese="僧侣"},
	{name="Priest",chinese="牧师"},
	{name="Bishop",chinese="教主"},
	{name="Sister",chinese="修女"},
	{name="Saintess",chinese="圣女"},
	{name="Sorcer",chinese="男法师"},
	{name="Sorceress",chinese="女法师"},
	{name="Wizard",chinese="男巫师"},
	{name="Witch",chinese="女巫"},
	{name="Siren",chinese="女海妖"},
	{name="Sage",chinese="贤者"},
	{name="Conjurer",chinese="妖术师"},
	{name="Shaman",chinese="祈祷师"},
	{name="Druid",chinese="德鲁伊"},
}

--特效表
specialEffectList={
	{"knightBreak","isKnight"},--破骑武器
	{"armorBreak","isArmor"},--破甲武器
	{"antiAir","isAirForce"},--对空武器
	{"dragonSlay","isDragon"},--杀龙武器
	{"ballistaBreak","isBallista"},--杀弩车武器
	{"monsterSlay","isMonster"},--杀怪武器
}
